[package]
name = "cosmwasm-math-compat"
authors = ["Chris Ricketts <chris_ricketts@protonmail.com>"]
version = "0.1.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", branch = "secret" }
schemars = "0.8.1"
serde = { version = "1.0.114", default-features = false, features = [
  "derive",
  "alloc"
] }
snafu = { version = "0.6.3" }
uint = "=0.9.3"
