[workspace]
members = [
    "packages/shadeswap-shared",
    "contracts/amm_pair",
    "contracts/factory",
    "contracts/router"
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true