[package]
name = "network-integration"
version = "0.1.0"
authors = ["Tony Nguyen <tnguyen@polarity.exchange>"]
edition = "2018"

[[bin]]
name = "deploy"
path = "src/launch/deploy.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []

[[bin]]
name="scrtcli"
path="src/launch/scrtcli.rs"

[dependencies]
colored = "2.0.0"
chrono = "0.4.19"
secretcli = { version = "0.1.0", path = "../secretcli" }
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", branch = "secret" }
serde = { version = "1.0.114", default-features = false, features = [
  "derive",
  "alloc"
] }
serde_json = { version = "1.0.67"}
getrandom = { version = "0.2", features = ["js"] } # Prevents wasm from freaking out when running make
rand = { version = "0.8.4"}
rs_merkle = { git = "https://github.com/FloppyDisck/rs-merkle", branch = "node_export" }
query-authentication = {git = "https://github.com/securesecrets/query-authentication", tag = "v1.2.0"}
shadeswap-shared = {path = "../shadeswap-shared"}
snip20-reference-impl = {path ="../../contracts/snip20"}
schemars = "0.8.1"
secret-toolkit = { git = "https://github.com/scrtlabs/secret-toolkit", branch = "cosmwasm-v1.0", features = [
  "permit",
  "viewing-key",
  "crypto",
] }